### PR TITLE
Implement Auto Labeler GitHub Action for Issues and Pull RequestsLabel

### PR DESCRIPTION
**Pull request by shubhagarwal1**
Overview
This pull request introduces an Auto Labeler GitHub Action that automatically assigns labels to issues and pull requests based on specific keywords found in their titles or bodies. This feature aims to streamline issue tracking and enhance project organization.

Changes Made
Added a new GitHub Actions workflow that triggers on issue creation and PR opening/editing.
Defined a set of keyword-label mappings to apply the appropriate labels, including:
Bug
Enhancement
Feature
Hacktoberfest
Hacktoberfest-accepted
GSSOC-EXT
Implemented logic to check the title and body for these keywords and apply labels accordingly.
Testing
I have tested the workflow by creating issues and PRs with the defined keywords to ensure that all labels are correctly applied. The workflow has been successfully triggered and functions as expected.

Next Steps
I recommend merging this PR to enable the Auto Labeler in our repository. This will help maintain clarity in issue categorization and improve collaboration.

Thank you for reviewing my changes!

### CODE REVIEW

**Comment by shubhagarwal1** [comment]
@c0sm0void please approve my commit

**Review by whyvineet — APPROVED** [review]

**Comment by c0sm0void** [comment]
> @c0sm0void please approve my commit

in README, the recent activity section doesn't belong to this repo. Please check or remove that code.

**Comment by c0sm0void** [comment]
> > > @c0sm0void please approve my commit
> > 
> > 
> > in README, the recent activity section doesn't belong to this repo. Please check or remove that code.
> 
> i have not done any changes to readme file

I know you haven't. well no problem. Let me look into that. Thanks

**Comment by shubhagarwal1** [comment]
> > > > @c0sm0void please approve my commit
> > > 
> > > 
> > > in README, the recent activity section doesn't belong to this repo. Please check or remove that code.
> > 
> > 
> > i have not done any changes to readme file
> 
> I know you haven't. well no problem. Let me look into that. Thanks

@c0sm0void Thank you for the opportunity.

**Pull request merged**
