### PR TITLE
I have updated the requirement from python version 3.6 to 3.12

### PR DESCRIPTION
**Pull request by trishap-16**
#6  
I have updated the requirement from python version 3.6 to 3.12 and made changes in deprecated lines in v3.12

### CODE REVIEW

**Comment by c0sm0void** [comment]
@trishap-16 please refer it to the assigned issue no#

**Comment by trishap-16** [comment]
#6 
I have updated the requirement from python version 3.6 to 3.12 and made changes in deprecated lines in v3.12

**Comment by c0sm0void** [comment]
@whyvineet @mvp-2003 Please verify the change. I think the level will be degraded to level 1-2 with these changes.
Expecting more changes as per the functionality of the project.

**Comment by whyvineet** [comment]
> @whyvineet @mvp-2003 Please verify the change. I think the level will be degraded to level 1-2 with these changes. Expecting more changes as per the functionality of the project.

I'm currently testing the changes! I think we should be degraded to level 1 with these changes if the test passes!

**Comment by c0sm0void** [comment]
Hi @trishap-16  , I can see with the latest 3.12 it's not compatible especially as it used virtual Python space to work in 3.6.
Could you please make every script and requirement compatible, in that case, we can make it level 3?

**Comment by whyvineet** [comment]
Hey @trishap-16 

**This PR is a commendable initial step towards upgrading the bot from Python 3.6 to 3.12. However, it is currently incomplete and may introduce potential issues for future contributors.**

### Specific Concerns:

- **Incompleteness**: The PR does not appear to address all the necessary changes to ensure full compatibility with Python 3.12. This includes potential updates to libraries, code refactoring, and handling of deprecated features.
- **Future Contributor Impact**: If this PR is merged in its current state, it could create confusion and additional work for future contributors who may need to address the remaining upgrade tasks.

**Pull request closed without merging**
