### PR TITLE
fix issue #69

### PR DESCRIPTION
**Pull request by whyvineet**

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
add level labels @c0sm0void 
Regards ,
Community Manager gssoc-ext

**Comment by c0sm0void** [comment]
> add level labels @c0sm0void Regards , Community Manager gssoc-ext

hey @AKSHITHA-CHILUKA , will remove the label to avoid confusion. This is fixed by a mentor.

**Comment by AKSHITHA-CHILUKA** [comment]
Thanks @c0sm0void

**Comment by AKSHITHA-CHILUKA** [comment]
Also please review all the pr as the program is coming to an end , so even if there are minmal changes do check the points on the leaderboard and assign them with at least level1 just to encourage them towards open source .
Just verify all the prs with crt labels

**Pull request merged**
