### PR TITLE
Github actions for more connectivity!

### LINKED ISSUE #95: Github actions for more connectivity!
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @c0sm0void 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

### PR DESCRIPTION
**Pull request by smog-root**
Closes #95 

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @rohitinu6 

_**Note**_: Add all the labels and assign me to this PR !!

### CODE REVIEW

**Comment by smog-root** [comment]
**Proof**:

**Issue open and close:**

Screenshot 2024-10-21 152058
<br>

**PR raise and  merged:**
Screenshot 2024-10-21 160211

**Comment by smog-root** [comment]
@c0sm0void merge it!!

**Comment by c0sm0void** [comment]
@smog-root have you gone through the comments and required changes?

**Comment by smog-root** [comment]
@c0sm0void what changes??

**Comment by c0sm0void** [comment]
> @c0sm0void what changes??
> 
> everything is working perfectly!! fine!

Well everything not fine. You haven't read my comments.

**Comment by smog-root** [comment]
@c0sm0void kindly assign this PR to me! there some issues in my leaderboard profile!

**Pull request merged**
