### PR TITLE
Added Table of Contents in Readme file

### PR DESCRIPTION
**Pull request by Maryam0330**
# Description
I have added the Table of Contents section to the README file. This improvement enhances the overall structure and allows for more intuitive navigation, making it easier for users to quickly find and access specific sections."

Fixes: #71

### CODE REVIEW

**Comment by Maryam0330** [comment]
@c0sm0void I have added the `Table of Contents` section under #71 issue. Please merge it.

**Comment by c0sm0void** [comment]
@Maryam0330 do me a favour, please update the Repository Structure as well. Then will approve this. Thanks

**Comment by Maryam0330** [comment]
@c0sm0void I'm new to open-source contribution so I'm a bit confused. Could you please explain exactly what I need to do?

**Comment by c0sm0void** [comment]
@Maryam0330  no worries!
there is this section in README which consists of folder structure of this repo. You can search how to update this thing, it's ez pz.
image

**Comment by Maryam0330** [comment]
@c0sm0void I have updated the `Repository Structure`. Please feel free to review and merge the changes.

**Review by c0sm0void — APPROVED** [review]

**Pull request merged**
