### PR TITLE
GitHub action PR Issue checker

### LINKED ISSUE #91: Adding github action workflow for PR validation
**The workflow checks consist of following steps-**

- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include `Fixes #NEW`

@c0sm0void
Pls assign me this issue give me labels like gssoc-extd,hacktoberfest,level3

### PR DESCRIPTION
**Pull request by ygowthamr**
**What i have done :**
- Solved Adding GitHub action workflow for PR validation

Fixes #91

@c0sm0void
Pls add me labels like gssoc-extd,level2,hacktoberfest.

### CODE REVIEW

**Review by c0sm0void — APPROVED** [review]

**Comment by whyvineet** [comment]
Working well when we don't give any description
Screenshot from 2024-10-17 23-49-49

While Giving the issue number the workflow is still giving error!
Screenshot from 2024-10-17 23-49-03

I'm not sure if this is case-sensitive or not but make sure it should be case-sensitive
Screenshot from 2024-10-17 23-49-24

**Review by whyvineet — CHANGES_REQUESTED** [review]
Make sure to fix all the errors mentioned in the above comment!

**Comment by ygowthamr** [comment]
@whyvineet 

This are not errors if fix is not mentioned in the description then this will occur

**Comment by ygowthamr** [comment]
> Working well when we don't give any description
> Screenshot from 2024-10-17 23-49-49
> 
> While Giving the issue number the workflow is still giving error!
> Screenshot from 2024-10-17 23-49-03
> 
> I'm not sure if this is case-sensitive or not but make sure it should be case-sensitive
> Screenshot from 2024-10-17 23-49-24
> 
> 

@whyvineet 

Here you just kept like fix #2 right, so it is asking you to keep in fixes #2

**Comment by ygowthamr** [comment]
@whyvineet 
Please check now i have updated the code

**Comment by ygowthamr** [comment]
@whyvineet @c0sm0void @mvp-2003 

Anyone pls check and merge my pr

**Review by whyvineet — APPROVED** [review]

**Pull request merged**
